# Site settings
title: "Tom Austin's Portfolio"
description: "The professional portfolio of Tom Austin, IT Specialist and author."
url: "https://tomaustin94.github.io"
baseurl: "" # Leave this empty for user sites

# Author settings
author:
  name: "Tom Austin"
  avatar: "https://github.com/tomaustin94.png" # GitHub profile picture URL
  bio: "IT Specialist, author, and photographer based in the UK."

# Social media links
social:
  - name: "GitHub"
    url: "https://github.com/tomaustin94?tab=repositories"
    icon: "fab fa-github"
  - name: "Medium"
    url: "https://medium.com/@TomTalksIT"
    icon: "fab fa-medium"
  - name: "Amazon Book"
    url: "https://www.amazon.com/dp/B0DCL1F5J2"
    icon: "fas fa-book"

# Theme settings
remote_theme: "daattali/beautiful-jekyll@6.0.1" # Use the remote theme feature

# Plugins
plugins:
  - jekyll-remote-theme

# Other settings
markdown: kramdown
highlighter: rouge
permalink: pretty
