# Site settings
title: "Tom Talks IT"
description: "The professional portfolio of Tom Austin, IT Specialist and author."
url: "https://tomaustin94.github.io"
baseurl: "" # Leave this empty for user sites

author: "Tom Austin"


################
# --- Logo --- #
################

# Image to show in the navigation bar - works best with a square image
# Remove this parameter if you don't want an image in the navbar
avatar: "https://github.com/tomaustin94.png"
# By default, the image is cut into a circle. You can disable this behaviour by setting 'round-avatar: false'
round-avatar: true

# If you want to have an image logo in the top-left corner instead of having the title of the website,
# then specify the following parameter
#title-img: /path/to/image

navbar-links:
  Github : "https://github.com/tomaustin94?tab=repositories"
  Medium: "https://medium.com/@TomTalksIT"
  Books:   
    - Learn Python in 30 days Book: "https://www.amazon.com/dp/B0DCL1F5J2"
  now: now
# Theme settings
remote_theme: "daattali/beautiful-jekyll@6.0.1" # Use the remote theme feature

# Plugins
plugins:
  - jekyll-remote-theme

# Other settings
markdown: kramdown
highlighter: rouge
permalink: pretty
